```{r}

library(data.table)
library(ggplot2)
library(scales) 
model1<-read.csv("model1.csv")
model1$date_range_start<-as.Date(model1$date_range_start,"%Y-%m-%d")
model1$date_range_end<-as.Date(model1$date_range_end,"%Y-%m-%d")
```

```{r}
combined<-subset(model1, select=c(safegraph_place_id,raw_visitor_counts,UNIT_NAME,PARKNAME,location_name, covid_era))
combined[is.na(combined)] <- 0
aggdata <-aggregate(raw_visitor_counts~., data=combined, mean, na.rm=TRUE)

aggdata_precovid<-aggdata[(aggdata$covid_era==F),]
aggdata_precovid$covid_era<-"Before COVID19"
aggdata_covid<-aggdata[(aggdata$covid_era==T),]
aggdata_covid$covid_era<-"During / After COVID"
aggdata<-rbind(aggdata_precovid,aggdata_covid)

```

```{r}
model1_precovid<-model1[(model1$date_range_start<"2020-03-01"),]
model1_precovid$covid_era<-"Before COVID19"
model1_covid<-model1[(model1$date_range_start>="2020-03-01"),]
model1_covid$covid_era<-"After COVID19"
model1<-rbind(model1_covid,model1_precovid)
```


```{r}
ggplot(aggdata, aes(x=covid_era,y=raw_visitor_counts,fill=PARKNAME)) + ylab("average monthly visitors")+xlab("")+
  geom_bar(stat="identity",position=position_dodge())+theme(legend.position="bottom", legend.text=element_text(size=6), legend.title = element_blank(),
       legend.key.size = unit(0.5, 'cm'))+ guides(colour = guide_legend(nrow = 6))
```
```{r}
ggplot(aggdata, aes(fill=covid_era,y=raw_visitor_counts,x=PARKNAME)) + ylab("average monthly visitors")+xlab("Park Name")+
  geom_bar(stat="identity",position=position_dodge())+theme(axis.text.x = element_text(angle = 90), legend.title = element_blank())
```
```{r}
ggplot(model1, aes(fill=covid_era,y=raw_visitor_counts,x=PARKNAME)) + ylab("monthly visitors")+xlab("Park Name")+
  geom_boxplot(outlier.colour="red", outlier.shape=4,
                outlier.size=0.8)+theme(legend.position="bottom",axis.text.x = element_text(angle = 90), legend.title = element_blank())
```

