
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read packages

```{r,warning=FALSE,message=FALSE, include=FALSE}
library(data.table)
library(tidyverse)
library(rmarkdown)
library(ggplot2)
library(plyr)
library(dplyr)
library(tibble)
library(jmuOutlier)
library(Epi)
library(geosphere)
library(bit64)
options(scipen = 999)
```


## read the files
```{r}
aggragated <- read.csv("national_park_visitation_analysis_w_mobile_phone_data/volume/data/processed/aggregated_records_based_on_census_block_groups.csv
")
aggragated<-subset(aggragated, select = -c(X))
relevant_census <- read.csv("national_park_visitation_analysis_w_mobile_phone_data/volume/data/processed/census_info.csv")
relevant_census <- subset(relevant_census, select = -c(X))
population<-read.csv("national_park_visitation_analysis_w_mobile_phone_data/volume/data/raw/census_files/population_data.csv")
area<-read.csv("national_park_visitation_analysis_w_mobile_phone_data/volume/data/interim/census_files_cleaned_and_computed/area_data.csv")
```

## Merge census data with visitation records 
```{r}
data_merge1<-merge(x = aggragated, y = relevant_census, by.x = "vistor_census_block", by.y="Geo_FIPS", all.x = TRUE)
```

## Read the coordinate files for the census block group
```{r}
coordinates<-read.csv("cbg_geographic_data.csv")
coordinates<-subset(coordinates, select = -c(amount_land, amount_water))
names(coordinates)[names(coordinates) == "longitude"] <- "census_longitude"
names(coordinates)[names(coordinates) == "latitude"] <- "census_latitude"

```

## Add census block group coordiantes to our dataset 
```{r}
data_merge2<-merge(x = data_merge1, y = coordinates, by.x = "vistor_census_block", by.y="census_block_group", all.x = TRUE)
```


## obtain distance from national parks to census block group
```{r}
data_merge2<-data_merge2 %>%  
    mutate(dist = distHaversine(cbind(census_longitude, census_latitude), cbind(park_longitude, park_latitude)))
```

## merge with population dataset
```{r}
data_merge3<-merge(x=data_merge2, y=population,  by.x = "vistor_census_block", by.y="Geo_FIPS", all.x=T)
```

## Merge with Park Area dataset
```{r}
data_merge4<-merge(x=data_merge3, y=area,  by.x = "PARKNAME", by.y="PARKNAME", all.x=T)
```


## Read the files
```{r}
write.csv(data_merge3, file = 'national_park_visitation_analysis_w_mobile_phone_data/volume/data/processed/processed_model.csv')
```
