---
author: "Charles Alba"
date: "January 30, 2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(data.table)
#install.packages('R.utils')
```

# reading the filtered POIs data which was resulted from step_1
```{r}

data<-read.csv("national_park_visitation_analysis_w_mobile_phone_data/volume/data/interim/filtered_pois/filtered_POIs_based_on_geometry/small_filtered_pois.csv")
data<-subset(data,!is.na(data$latitude))
data<-subset(data,!is.na(data$longitude))
data<-subset(data,select=-c(X, naics_code, UNIT_TYPE, pPolyID))
list_name<-data$safegraph_place_id

```



# reading and subsetting the patterns data from 2018 - 2021
```{r}
safegraph1<-fread("patterns_comb.csv.gz")
safegraph1<-data.table(safegraph1)
safegraph1<-subset(safegraph1,select=c(date_range_start, date_range_end,safegraph_place_id,raw_visitor_counts))
safegraph1<-safegraph1[(safegraph1$safegraph_place_id %in% list_name),]


```

# Merge  
```{r}
safegraph_comb_05_18<-merge(safegraph_comb, data,by.x="safegraph_place_id",by.y="safegraph_place_id",all.x=T)
write.csv(safegraph_comb,'national_park_visitation_analysis_w_mobile_phone_data/volume/data/interim/filtered_pois/filtered_pois_based_on_count/aggragated_count.csv')
```

