```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,warning=FALSE,message=FALSE, include=FALSE}
library(data.table)
library(tidyverse)
library(rmarkdown)
library(ggplot2)
library(plyr)
library(lsmeans)
library(multcompView)
library(lmtest)
library(nortest)
library(MASS)
library(olsrr)
library(nortest)
library(lsmeans)
library(multcompView)
library(lme4)
library(lmerTest)
library(text2vec)
library(pdist)
library(olsrr)
library(MASS)
library(dplyr)
library(tibble)
library(jmuOutlier)
library(Epi)
library(geosphere)
library(bit64)
options(scipen=999)
```



```{r}
model1<-read.csv("model1.csv")
model1$date_range_start<-as.Date(model1$date_range_start,"%Y-%m-%d")
model1$date_range_end<-as.Date(model1$date_range_end,"%Y-%m-%d")
model1_precovid<-model1[(model1$date_range_start<"2020-03-01"),]
model1_precovid$covid_era<-F
model1_covid<-model1[(model1$date_range_start>="2020-03-01"),]
model1_covid$covid_era<-T
model1<-rbind(model1_covid,model1_precovid)
write.csv(model1,"model1.csv")
```



